### ISSUE TITLE
Escrever a documentação

### ISSUE THREAD

**Issue by malukenho** [dindigital/DataAccessLayer#1]
Seria bem mais fácil de usar a biblioteca, se ela tivesse um mínimo de documentação, ou pelo menos exemplos práticos.

[]'s

**Comment by jaircuevajunior** [comment]
Hey man, desculpe a demora. Seria mto melhor né?...
É que estamos ainda iniciando em alguns assuntos (open source, TDD...)

Ficaria muito grato se pudesse contribuir com alguma coisa, mas creio que teremos que fazer um mínimo de documentação, como você bem falou...
